version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "5000:5000"
    networks:
      - ecommerce-network
    depends_on:
      - db

  order-service:
    build: ./order-service
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
    depends_on:
      - db


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - ecommerce-network
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  ecommerce-network:

volumes:
  db_data:
